[package]
name = "karyakarta"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
cortex-a = "*"
spin = "0.9"
volatile = "0.4"

[dependencies.lazy_static]
version="*"
features = ["spin_no_std"]

